[package]
name = "minimappers2"
version = "0.1.5"
edition = "2021"

[lib]
name = "minimappers2"
crate-type = ["cdylib", "rlib"]

[dependencies]
minimap2 = { version = "0.1.17", features = ["simde"] }
crossbeam = "0.8.4"
mimalloc = {version = "0.1.39", default-features = false }

pyo3 = { version = "0.20.0" }
polars = "0.35.4"
pyo3-polars = "0.9.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units  = 1

[profile.dev]
debug = true

[profile.dev.package."*"]
opt-level = 3

[features]
default = ["pyo3/extension-module", "pyo3/abi3-py37"]
